import React from 'react';
import { Container, Row, Stack } from 'react-bootstrap';

const About: React.FC = () => {
    return (
        <Container>
            <Row className="my-4 mx-5">
                <h1>About</h1>
                <p>BotFaktory serves as a platform for users to easily create chatbots powered by the same technology that powers Chat-GPT. The main use case of this application is to create chatbots with customisable knowledge base and characteristics defined by the user.</p>
            </Row>
            <Row className="my-4 mx-5">
                <h1>Disclaimer</h1>
                <p>The chatbots uses the chat completion API provided by OpenAI to generate responses based on the inputs provided by the user. While we strive to provide the best possible experience to our users, it is important to note that there are limitations and potential biases that may affect the accuracy of the responses generated by the chatbot.</p>
                <p>The responses generated by our chatbot are based on the information available in the model's training data, and may not always reflect the most up-to-date or accurate information. Additionally, the chatbot's responses may be affected by the biases present in the training data, which may result in responses that are insensitive or inaccurate.</p>
                <p>We are committed to adhering to OpenAI's policies regarding the use of their APIs, and we urge our users to do the same. We also recommend that users exercise caution when relying on the responses generated by the chatbot, and that they verify the accuracy of the information before acting on it.</p>
                <p>Please note that our chatbot is intended for informational purposes only, and should not be used as a substitute for professional advice or medical diagnosis. We are not responsible for any damages or losses that may result from the use of our chatbot application.</p>
                <p></p>
            </Row>
        </Container>
    )
}

export default About;